### ISSUE TITLE
Requires a '4D Web Application Expansion for 4D Client' to use on 4D Client

### ISSUE THREAD

**Issue by sp00ndogger** [4d/4D-NetKit#1]
When intending to implement this in a call from a 4D CLIENT application (aka Remote Mode), you will need a **4D Web Application Expansion for 4D Client** license, not the standard **4D Web Application Expansion** included as part of 4D Server license.

<img width="405" alt="2 en" src="https://user-images.githubusercontent.com/24779852/156458519-dff4293c-c716-445a-899c-2df299e4c1fb.png">

Just thought it should b mentioned somewhere because the blog post announcing this does not, nor does it seem to be mentioned anywhere here.

**Comment by yannicktrinh** [comment]
No Web Server license is required since version 4D 19R7. The Web Server is now working in a "downgraded" mode (limited to 5 requests per minute), just enough to be able to process the response of the Server pointed by the authenticateURI
