### ISSUE TITLE
Issue when redirect does not ends with `/`

### ISSUE THREAD

**Issue by Ganbin** [4d/4D-NetKit#20]
When the redirectUri do not ends with `/`, the regex for the path and the port in [_getPathFromURL](https://github.com/4d/4D-NetKit/blob/7c0bfa1c6c045ef7950eebef2eea9df45d4ae02b/Project/Sources/Methods/_getPathFromURL.4dm) and in [_getPortFromURL](https://github.com/4d/4D-NetKit/blob/7c0bfa1c6c045ef7950eebef2eea9df45d4ae02b/Project/Sources/Methods/_getPortFromURL.4dm) are not working correctly.

Ex: `http://127.0.0.1:8081`

It should accept such redirectUri.

**Comment by yannicktrinh** [comment]
Fixed in main
