### ISSUE TITLE
`WebFolder/index.html` created on the first webServer start

### ISSUE THREAD

**Issue by Ganbin** [4d/4D-NetKit#21]
When I use the component, a `WebServer` folder with the default `index.html` file are created.

This prevent my redirect to works because the redirect will return this `index.html` page instead of going through the `On Web Connection` database method.

My redirect URI is `http://127.0.0.1:8081/`

I have to delete manually the `WebFolder` to make it works.

**Comment by e-marchand** [comment]
Hi, it’s a 4D behavior, not directly related to this component code

For me it’s a bad idea to not add a path in the url
Any code to manage the authentification must be run after checking that url path from the request match
For instance http://127.0.0.1:8081/oauth/callback

(The only things that this component could do is to warn about that)
