### ISSUE TITLE
DEV

### ISSUE THREAD

**Issue by fabrice-mainguene** [4d/4D-NetKit#25]
Pushed in branch [YT/Feature/Office365_UpdateMessage](https://github.com/4d/4D-NetKit/tree/YT/Feature/Office365_UpdateMessage)

**Comment by yannicktrinh** [comment]
[YT/Feature/Office365_UpdateMessage](https://github.com/4d/4D-NetKit/tree/YT/Feature/Office365_UpdateMessage) merged in Main
