### ISSUE TITLE
adopt more traditional version labeling

### ISSUE THREAD

**Issue by macMikey** [4d/4D-NetKit#62]
it would be great if you would use a more traditional version labeling scheme, and then, if a version was dependent upon a particular version of 4d, add that to the readme/release notes.
right now, for instance, you have R5 as the version level, but R4 is still in beta, R5 is not available, and it doesn't look like there is anything in R5 that won't run in prior versions.
i get that netkit is supposed to be an internal component, but there are features and bugfixes that apply to prior versions, too.

**Comment by macMikey** [comment]
the thing i'm thinking about are when hotfixes, like PR63 hit (assuming that it is accepted), they might need to be applied to multiple versions.
since netkit is supposed to be an internal component, i get lining it up with the branches. it just seems like more work to have to cherrypick hotfixes onto each of the supported branches.

**Comment by e-marchand** [comment]
I understand the point and I somewhat agree
We use another VCS before Git and we keep this flat way to proceed.

For my component until there is no real change, I synchronise my 20R. branch with the main. But I am the only one.

**Comment by macMikey** [comment]
on, that's right. i forgot you guys didn't use git for everyday tasks.
nothing to see here. move along.
